project:
  type: website
  execute-dir: project
  render:
    - index.qmd
    - chapters/chapter1.qmd
    - chapters/chapter2.qmd
    - chapters/chapter3.qmd

website:
  page-navigation: true
  title: "Introduction to Cross-Validation"

  site-url: "https://AIML4OS.github.io/AIML4OS-template-quarto-r"
  repo-url: "https://github.com/AIML4OS/AIML4OS-template-quarto-r"
  repo-actions: [edit, source, issue]

  sidebar:
    logo: resources/profile/main3.png
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Introduction
      - href: chapters/chapter1.qmd
        text: Why cross-validation matters
      - href: chapters/chapter2.qmd
        text: Standard methods
      - href: chapters/chapter3.qmd
        text: Cross-validation based on data structure

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

filters:
  - export-metadata.lua